include: package:lint/analysis_options_package.yaml

analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
  language:
    strict-raw-types: true
  exclude:
    - "**/*.g.dart"

linter:
  rules:
    - avoid_catches_without_on_clauses
    - avoid_equals_and_hash_code_on_mutable_classes
    - avoid_renaming_method_parameters
    - avoid_returning_null
    - avoid_slow_async_io
    - avoid_types_on_closure_parameters
    - cascade_invocations
    - close_sinks
    - flutter_style_todos
    - lines_longer_than_80_chars
    - literal_only_boolean_expressions
    - omit_local_variable_types
    - one_member_abstracts
    - only_throw_errors
    - prefer_adjacent_string_concatenation
    - prefer_asserts_with_message
    - prefer_foreach
    - prefer_int_literals
    - prefer_mixin
    - prefer_relative_imports
    - prefer_single_quotes
    - sort_constructors_first
    - unawaited_futures
    - unnecessary_lambdas
    - use_to_and_as_if_applicable
