name: core

environment:
  sdk: '>=2.9.0 <3.0.0'

dependencies:
  built_collection: ^4.3.2
  built_value: ^7.1.0
  redux: ^4.0.0

dev_dependencies:
  build_runner: ^1.10.0
  built_value_generator: ^7.1.0
  lint: ^1.2.0
  test: ^1.14.4
  gherkin: ^1.1.8
